// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	db "github.com/doanvuduy170921/quick-link/internal/infrastructure/db/sqlc"
	mock "github.com/stretchr/testify/mock"
)

// MockUrlRepository is an autogenerated mock type for the UrlRepository type
type MockUrlRepository struct {
	mock.Mock
}

type MockUrlRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUrlRepository) EXPECT() *MockUrlRepository_Expecter {
	return &MockUrlRepository_Expecter{mock: &_m.Mock}
}

// CreateURL provides a mock function with given fields: ctx, arg
func (_m *MockUrlRepository) CreateURL(ctx context.Context, arg db.CreateURLParams) (db.Url, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateURL")
	}

	var r0 db.Url
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateURLParams) (db.Url, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateURLParams) db.Url); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.Url)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateURLParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUrlRepository_CreateURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateURL'
type MockUrlRepository_CreateURL_Call struct {
	*mock.Call
}

// CreateURL is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateURLParams
func (_e *MockUrlRepository_Expecter) CreateURL(ctx interface{}, arg interface{}) *MockUrlRepository_CreateURL_Call {
	return &MockUrlRepository_CreateURL_Call{Call: _e.mock.On("CreateURL", ctx, arg)}
}

func (_c *MockUrlRepository_CreateURL_Call) Run(run func(ctx context.Context, arg db.CreateURLParams)) *MockUrlRepository_CreateURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateURLParams))
	})
	return _c
}

func (_c *MockUrlRepository_CreateURL_Call) Return(_a0 db.Url, _a1 error) *MockUrlRepository_CreateURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUrlRepository_CreateURL_Call) RunAndReturn(run func(context.Context, db.CreateURLParams) (db.Url, error)) *MockUrlRepository_CreateURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetOriginalUrlByShortCode provides a mock function with given fields: ctx, shortCode
func (_m *MockUrlRepository) GetOriginalUrlByShortCode(ctx context.Context, shortCode string) (db.GetOriginalUrlByShortCodeRow, error) {
	ret := _m.Called(ctx, shortCode)

	if len(ret) == 0 {
		panic("no return value specified for GetOriginalUrlByShortCode")
	}

	var r0 db.GetOriginalUrlByShortCodeRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (db.GetOriginalUrlByShortCodeRow, error)); ok {
		return rf(ctx, shortCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) db.GetOriginalUrlByShortCodeRow); ok {
		r0 = rf(ctx, shortCode)
	} else {
		r0 = ret.Get(0).(db.GetOriginalUrlByShortCodeRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, shortCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUrlRepository_GetOriginalUrlByShortCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOriginalUrlByShortCode'
type MockUrlRepository_GetOriginalUrlByShortCode_Call struct {
	*mock.Call
}

// GetOriginalUrlByShortCode is a helper method to define mock.On call
//   - ctx context.Context
//   - shortCode string
func (_e *MockUrlRepository_Expecter) GetOriginalUrlByShortCode(ctx interface{}, shortCode interface{}) *MockUrlRepository_GetOriginalUrlByShortCode_Call {
	return &MockUrlRepository_GetOriginalUrlByShortCode_Call{Call: _e.mock.On("GetOriginalUrlByShortCode", ctx, shortCode)}
}

func (_c *MockUrlRepository_GetOriginalUrlByShortCode_Call) Run(run func(ctx context.Context, shortCode string)) *MockUrlRepository_GetOriginalUrlByShortCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUrlRepository_GetOriginalUrlByShortCode_Call) Return(_a0 db.GetOriginalUrlByShortCodeRow, _a1 error) *MockUrlRepository_GetOriginalUrlByShortCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUrlRepository_GetOriginalUrlByShortCode_Call) RunAndReturn(run func(context.Context, string) (db.GetOriginalUrlByShortCodeRow, error)) *MockUrlRepository_GetOriginalUrlByShortCode_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUrlRepository creates a new instance of MockUrlRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUrlRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUrlRepository {
	mock := &MockUrlRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
