// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUseCase is an autogenerated mock type for the UseCase type
type MockUseCase struct {
	mock.Mock
}

type MockUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUseCase) EXPECT() *MockUseCase_Expecter {
	return &MockUseCase_Expecter{mock: &_m.Mock}
}

// GenerateKey provides a mock function with given fields: ctx, URL
func (_m *MockUseCase) GenerateKey(ctx context.Context, URL string) (string, error) {
	ret := _m.Called(ctx, URL)

	if len(ret) == 0 {
		panic("no return value specified for GenerateKey")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, URL)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, URL)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, URL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_GenerateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateKey'
type MockUseCase_GenerateKey_Call struct {
	*mock.Call
}

// GenerateKey is a helper method to define mock.On call
//   - ctx context.Context
//   - URL string
func (_e *MockUseCase_Expecter) GenerateKey(ctx interface{}, URL interface{}) *MockUseCase_GenerateKey_Call {
	return &MockUseCase_GenerateKey_Call{Call: _e.mock.On("GenerateKey", ctx, URL)}
}

func (_c *MockUseCase_GenerateKey_Call) Run(run func(ctx context.Context, URL string)) *MockUseCase_GenerateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUseCase_GenerateKey_Call) Return(_a0 string, _a1 error) *MockUseCase_GenerateKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_GenerateKey_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockUseCase_GenerateKey_Call {
	_c.Call.Return(run)
	return _c
}

// Redirect provides a mock function with given fields: ctx, code
func (_m *MockUseCase) Redirect(ctx context.Context, code string) (string, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Redirect")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUseCase_Redirect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Redirect'
type MockUseCase_Redirect_Call struct {
	*mock.Call
}

// Redirect is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockUseCase_Expecter) Redirect(ctx interface{}, code interface{}) *MockUseCase_Redirect_Call {
	return &MockUseCase_Redirect_Call{Call: _e.mock.On("Redirect", ctx, code)}
}

func (_c *MockUseCase_Redirect_Call) Run(run func(ctx context.Context, code string)) *MockUseCase_Redirect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUseCase_Redirect_Call) Return(_a0 string, _a1 error) *MockUseCase_Redirect_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUseCase_Redirect_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockUseCase_Redirect_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUseCase creates a new instance of MockUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUseCase {
	mock := &MockUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
