// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: click.sql

package db

import (
	"time"
)

type BatchInsertClickParams struct {
	ShortCode string    `json:"short_code"`
	ClickedAt time.Time `json:"clicked_at"`
}
