// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBatchInsertClick implements pgx.CopyFromSource.
type iteratorForBatchInsertClick struct {
	rows                 []BatchInsertClickParams
	skippedFirstNextCall bool
}

func (r *iteratorForBatchInsertClick) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBatchInsertClick) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ShortCode,
		r.rows[0].ClickedAt,
	}, nil
}

func (r iteratorForBatchInsertClick) Err() error {
	return nil
}

func (q *Queries) BatchInsertClick(ctx context.Context, arg []BatchInsertClickParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"clicks"}, []string{"short_code", "clicked_at"}, &iteratorForBatchInsertClick{rows: arg})
}
