// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	GetOriginalUrlByShortCode(ctx context.Context, shortCode string) (GetOriginalUrlByShortCodeRow, error)
}

var _ Querier = (*Queries)(nil)
