// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urls.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createURL = `-- name: CreateURL :one
insert into urls(
                    short_code,original_url,expires_at,created_at,user_id
)
values ($1,$2,$3,NOW(),$4)
returning id, short_code, original_url, created_at, expires_at, user_id
`

type CreateURLParams struct {
	ShortCode   string      `json:"short_code"`
	OriginalUrl string      `json:"original_url"`
	ExpiresAt   *time.Time  `json:"expires_at"`
	UserID      pgtype.Int8 `json:"user_id"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL,
		arg.ShortCode,
		arg.OriginalUrl,
		arg.ExpiresAt,
		arg.UserID,
	)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UserID,
	)
	return i, err
}

const getOriginalUrlByShortCode = `-- name: GetOriginalUrlByShortCode :one
SELECT original_url,expires_at
FROM urls
WHERE short_code = $1
AND (expires_at > NOW() OR expires_at IS NULL)
`

type GetOriginalUrlByShortCodeRow struct {
	OriginalUrl string     `json:"original_url"`
	ExpiresAt   *time.Time `json:"expires_at"`
}

func (q *Queries) GetOriginalUrlByShortCode(ctx context.Context, shortCode string) (GetOriginalUrlByShortCodeRow, error) {
	row := q.db.QueryRow(ctx, getOriginalUrlByShortCode, shortCode)
	var i GetOriginalUrlByShortCodeRow
	err := row.Scan(&i.OriginalUrl, &i.ExpiresAt)
	return i, err
}
